### PR TITLE
Rust version

### PR DESCRIPTION
**Pull request by royvegard**
Only the detail part for now.

### CODE REVIEW

**Comment by ianhbell** [comment]
Can you please fill out a README with a description of what you have done, how to compile/run the code, etc.?

**Comment by royvegard** [comment]
I added a [README.md](https://github.com/royvegard/AGA8/blob/master/AGA8CODE/RUST/README.md) to the RUST directory.

**Comment by ianhbell** [comment]
Can you please put your contact information in the README?  After that I'll merge.

**Comment by royvegard** [comment]
Contact info added.

**Comment by ianhbell** [comment]
Thank you very much, merging.  Can you please confirm that you are willing to license your work with a permissive license?

**Comment by royvegard** [comment]
Yes, I am willing to license my work with a permissive license.

**Comment by ianhbell** [comment]
Thanks!

**Pull request merged**
